### ISSUE TITLE
Bake nodemon into the sample app?

### ISSUE THREAD

**Issue by zeke** [probot/template#41]
The [current development docs](https://github.com/probot/probot/blob/0ebea0eaee58945ec84b560c1d9612f5aa695c90/docs/development.md) recommend setting up [nodemon](https://ghub.io/nodemon) for a more convenient dev experience. I generally agree with this recommendation, and think it might make sense to just bake `nodemon` right into this template, with an `npm run dev` script to boot.

@bkeepers mentioned some past issues with nodemon and express not cooperating, but we've been using the two on electronjs.org for a while and haven't had any trouble.

What do folks think of this idea? Worth it for the smoother onboarding, or too opinionated and/or bloated?

**Comment by bkeepers** [comment]
If it works well, I'm 👍 for trying it. If people don't want it or don't like it, they can remove it.

And to get a sense of the impact, it adds 200 packages (+45%) and 6MB (+7%):

```
$ npx create-probot-app
…

$ du -sh node_modules 
 90M	node_modules

$ npm install -D nodemon
…

+ nodemon@1.14.11
added 200 packages in 8.113s
                                                                                
$ du -sh node_modules   
 96M	node_modules
```

**Comment by JasonEtco** [comment]
I install `nodemon` on every new app I work on, so I'm +1 for this. I think we would also want to change the docs a bit to reflect such a change.

**Comment by itaditya** [comment]
:+1: for me too.
